Dummy UI 추가
wisemuji/android-clean-architecture-github-client pull request #7
Opened 2021-02-01 19:47 UTC by wisemuji

## Dummy UI 추가
⚠️ 마지막 7개 커밋 리뷰 부탁드립니다!
* 일부 누락된 의존성을 추가합니다
* Application class를 추가합니다
* 메인 화면 클래스 및 레이아웃을 추가합니다
![image](https://user-images.githubusercontent.com/32327475/106509865-7bc09480-6511-11eb-9328-13e5e5a9f627.png)

2021-02-02 11:05 UTC, BeokBeok requested changes
약간의 코맨트가 있습니다 😄 

---

공통으로 사용하는 코드들을 common 혹은 base.gradle 을 만드셔서 import 해서 사용하시면 좋을 것 같습니다 😄

2021-02-02 11:05 UTC, BeokBeok commented on app/src/main/java/com/wisemuji/githubclient/ui/main/MainViewModel.kt
> +    val username = MutableLiveData<String>("")
two way binding 을 사용하신 이유가 있나요?

2021-02-02 11:05 UTC, BeokBeok commented on app/src/main/java/com/wisemuji/githubclient/ui/main/MainViewModel.kt
> +            }
postValue 를 쓰신 이유가 무엇인가요?

2021-02-02 11:05 UTC, BeokBeok commented on app/src/main/res/layout/activity_main.xml
> +            app:layout_constraintEnd_toStartOf="@+id/main_searchButton"
```suggestion
            app:layout_constraintEnd_toStartOf="@id/main_searchButton"
```
id 를 참조하는 경우에는 + 를 사용하지 않는 것이 좋습니다 😄

2021-02-02 11:05 UTC, BeokBeok commented on app/src/main/res/layout/activity_main.xml
> +            android:id="@+id/main_searchEditText"
xml 에서는 snake case 가 컨벤션입니다 😄

2021-02-14 04:43 UTC, wisemuji commented on app/src/main/java/com/wisemuji/githubclient/ui/main/MainViewModel.kt
> +    val onError: LiveData<Throwable> = _onError
get()을 붙이지 않더라도 val이므로 재선언은 할 수 없고 LiveData 타입이므로 수정이 불가능하지 않나여?

2021-02-14 04:44 UTC, wisemuji commented on app/src/main/java/com/wisemuji/githubclient/ui/main/MainViewModel.kt
> +    val username = MutableLiveData<String>("")
나중에 검색 버튼 클릭 없이 자동 검색할 수 있도록 변경할 예정입니다!

2021-02-14 05:02 UTC, wisemuji commented on app/src/main/res/layout/activity_main.xml
> +            app:layout_constraintEnd_toStartOf="@+id/main_searchButton"
이건 https://github.com/wisemuji/android-clean-architecture-github-client/pull/8 여기서 반영될 것 같습니다!

2021-02-14 05:04 UTC, wisemuji commented on app/src/main/res/layout/activity_main.xml
> +            android:id="@+id/main_searchEditText"
혹시 컨벤션인건 어디서 확인할 수 있을까요? 저는 xml에서 원래 snake case만 사용할 수 있었는데 대문자도 사용할 수 있도록 추후에 업데이트 된걸로 알고 있었어서요!

2021-02-14 05:05 UTC, wisemuji commented
> 약간의 코맨트가 있습니다 😄
> 
> 공통으로 사용하는 코드들을 common 혹은 base.gradle 을 만드셔서 import 해서 사용하시면 좋을 것 같습니다 😄

감사합니다! 해당 리뷰는 이슈로 만들어 두겠습니다!!!!

참고로 리뷰 base branch 와 컨플릭트가 많이 나서 부득이하게 force push 를 하게 되었습니다

2021-02-14 05:06 UTC, wisemuji commented on app/build.gradle
> +        jvmTarget = JavaVersion.VERSION_1_8.toString()
https://github.com/wisemuji/android-clean-architecture-github-client/pull/7/commits/8caece365b712a7161dccb25d2293d858db33175 없어도 되는군요!!! 아래의 코멘트와 같이 반영했습니당 ㅎㅎ

2021-02-14 05:07 UTC, wisemuji commented on app/src/main/AndroidManifest.xml
>          android:allowBackup="true"
https://github.com/wisemuji/android-clean-architecture-github-client/pull/7/commits/615f108e7f6f18acd68efe87ec94124fee85d68f true로 하면 앱 삭제 후에 데이터가 남아있을 수 있군용 감사해여!

2021-02-14 05:08 UTC, wisemuji commented on app/src/main/java/com/wisemuji/githubclient/ui/main/MainViewModel.kt
> +            }
https://github.com/wisemuji/android-clean-architecture-github-client/pull/7/commits/2b9990691b84081d1859d4dcfe9a4397b271ede5 😅😅😅😅 감사해영 ㅎㅎ

2021-02-14 06:59 UTC, BeokBeok commented on app/src/main/AndroidManifest.xml
>          android:allowBackup="true"
두두님에게도 리뷰를 드린 부분인데요
이 부분은 cve 에 등록이 되어 있기도 합니다 😄 
ref. https://nvd.nist.gov/vuln/detail/CVE-2017-16835

2021-02-14 06:59 UTC, BeokBeok commented on app/src/main/java/com/wisemuji/githubclient/ui/main/MainViewModel.kt
> +    val onError: LiveData<Throwable> = _onError
get() 을 사용하면 접근 시 _onError 의 getter 프로퍼티에 접근해서 사용하지만
get() 을 사용하지 않으면 호출할 때마다 매번 치환하는 과정을 거칩니다 😄 

ref. [Android LiveData의 사용법과 내부 코드를 통한 UI 처리, 중복 처리 등 살펴보기](https://thdev.tech/android/2021/02/01/LiveData-Intro/)

2021-02-14 06:59 UTC, BeokBeok commented on app/src/main/res/layout/activity_main.xml
> +            android:id="@+id/main_searchEditText"
[A successful XML naming convention](https://jeroenmols.com/blog/2016/03/07/resourcenaming/) 여기에 적혀있긴 합니다
혹시 대문자도 사용할 수 있다고 업데이트 된 것은 어디에서 보셨나요? 🤔

2021-02-14 07:00 UTC, BeokBeok reviewed
연휴임에도 코딩하시느라 고생이 많으십니다 😅 
코맨트를 추가하였습니다 😄

2021-02-14 15:30 UTC, wisemuji commented on app/src/main/res/layout/activity_main.xml
> +            android:id="@+id/main_searchEditText"
저는 회사 분께 들었습니다!!! 저렇게 아티클에서 권장하는거라면 snake case로 변경해도 좋을 것 같군용
어차피 프로젝트 초기이기 때문에 snake case건, camel case건 하나로 고정하는게 제일 베스트일 것 같네요!

2021-02-14 15:31 UTC, wisemuji commented on app/src/main/java/com/wisemuji/githubclient/ui/main/MainViewModel.kt
> +    val onError: LiveData<Throwable> = _onError
오호 내부에서는 저렇게 쓰이는군요! 감사합니당 🙇

2021-02-14 15:36 UTC, wisemuji commented on app/src/main/java/com/wisemuji/githubclient/ui/main/MainViewModel.kt
> +    val onError: LiveData<Throwable> = _onError
https://github.com/wisemuji/android-clean-architecture-github-client/pull/7/commits/fbac201719bee5b9ca0dbc30a6887f59324d9056 반영했어요!

2021-02-14 15:36 UTC, wisemuji commented on app/src/main/res/layout/activity_main.xml
> +            android:id="@+id/main_searchEditText"
https://github.com/wisemuji/android-clean-architecture-github-client/pull/7/commits/7f2a1574353bc1befca97dd7b4ebbe07ef64479d 감사합니다 🙇

2021-02-14 15:36 UTC, wisemuji commented
> 연휴임에도 코딩하시느라 고생이 많으십니다 😅
> 코맨트를 추가하였습니다 😄

저야말로 리뷰 항상 감사합니다 🙏

2021-02-15 12:22 UTC, BeokBeok approved these changes
LGTM 👊 ✌️ 🖐️

2021-02-21 04:17 UTC, merged